version: '3.5'

services:
    app:
        build: ./docker/images/php81
        volumes:
            - ./application:/var/www/html
            - ./docker/images/php81/files/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        ports:
            - "6040:8000"
        links:
            - postgresql
#            - supervisor
        networks:
            - cluster
        working_dir: /var/www/html
        restart: always
    postgresql:
        image: postgres:14.1-alpine
        ports:
            - "5425:5432"
        networks:
            - cluster
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: pQLkm8NOkS0gOBox
            POSTGRES_DB: clever
        volumes:
            - ./docker/images/postgres/files/postgresql.conf:/etc/postgresql.conf
        command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
        restart: always
#    supervisor:
#        build: ./docker/images/supervisor
#        working_dir: /var/www/html
#        restart: unless-stopped
#        volumes:
#            - ./application:/var/www/html
#            - ./docker/images/supervisor/files:/etc/supervisor/conf.d/
#        ports:
#            - "8006:8008"
#        networks:
#            - cluster
networks:
    cluster:
        name: cluster
        external: true
        driver: bridge

